import { gsap } from "gsap";
import {
    ScrollTrigger,
    Draggable,
    MotionPathHelper,
    MotionPathPlugin,
    Flip,
    CustomEase,
    InertiaPlugin,
    SplitText,
    GSDevTools,
    ScrollSmoother,
    DrawSVGPlugin,
    MorphSVGPlugin,
    Observer,
    ScrambleTextPlugin,
} from "gsap/all";

export {
    gsap,
    ScrollTrigger,
    Draggable,
    MotionPathPlugin,
    Flip,
    CustomEase,
    InertiaPlugin,
    SplitText,
    GSDevTools,
    ScrollSmoother,
    MotionPathHelper,
    DrawSVGPlugin,
    MorphSVGPlugin,
    Observer,
    ScrambleTextPlugin,
};
