name: Create Release on package.json Update

on:
    push:
        paths:
            - "package.json"

jobs:
    create-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Get package version
              id: get_version
              run: |
                  version=$(jq -r .version package.json)
                  echo "version=$version" >> $GITHUB_ENV

            - name: Create GitHub Release
              uses: elgohr/Github-Release-Action@v5
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  title: "Release v${{ env.version }}"
                  tag: "v${{ env.version }}"
                  prerelease: false
